#!/usr/bin/env tsx
import { createHash, randomBytes } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { config } from 'dotenv';
import { exchangeTooLostAuthorizationCode } from '../src/lib/tooLostOAuth';

config({ path: resolve(process.cwd(), '.env.local') });

const AUTHORIZE_URL = 'https://toolost.com/oauth/authorize';
function base64Url(value: Buffer): string {
  return value.toString('base64url');
}

function requireEnvironment(name: 'TOOLOST_CLIENT_ID' | 'TOOLOST_REDIRECT_URI'): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not configured in .env.local.`);
  return value;
}

function buildAuthorizationUrl(clientId: string, redirectUri: string, state: string, challenge: string): string {
  const url = new URL(AUTHORIZE_URL);
  url.searchParams.set('response_type', 'code');
  url.searchParams.set('client_id', clientId);
  url.searchParams.set('redirect_uri', redirectUri);
  url.searchParams.set('scope', 'read:releases');
  url.searchParams.set('state', state);
  url.searchParams.set('code_challenge', challenge);
  url.searchParams.set('code_challenge_method', 'S256');
  return url.toString();
}

async function main() {
  const clientId = requireEnvironment('TOOLOST_CLIENT_ID');
  const clientSecret = process.env.TOOLOST_CLIENT_SECRET || undefined;
  const redirectUri = requireEnvironment('TOOLOST_REDIRECT_URI');
  const verifier = base64Url(randomBytes(64));
  const challenge = base64Url(createHash('sha256').update(verifier).digest());
  const state = base64Url(randomBytes(32));
  const authorizationUrl = buildAuthorizationUrl(clientId, redirectUri, state, challenge);

  console.log('\nopen this url and approve read-only release access:\n');
  console.log(authorizationUrl);
  console.log('\nthen paste the full callback url.\n');

  const prompt = createInterface({ input: stdin, output: stdout });
  const callbackValue = (await prompt.question('callback url: ')).trim();
  prompt.close();

  const callbackUrl = new URL(callbackValue);
  const expectedRedirect = new URL(redirectUri);
  const normalizePathname = (pathname: string) => pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  if (
    callbackUrl.origin !== expectedRedirect.origin
    || normalizePathname(callbackUrl.pathname) !== normalizePathname(expectedRedirect.pathname)
  ) {
    throw new Error('Callback URL does not match TOOLOST_REDIRECT_URI.');
  }
  if (callbackUrl.searchParams.get('state') !== state) throw new Error('OAuth state did not match. Start again.');

  const providerError = callbackUrl.searchParams.get('error');
  if (providerError) throw new Error(`Too Lost authorization failed: ${providerError}.`);

  const code = callbackUrl.searchParams.get('code');
  if (!code) throw new Error('Callback URL does not contain an authorization code.');

  const token = await exchangeTooLostAuthorizationCode({
    clientId,
    clientSecret,
    code,
    redirectUri,
    codeVerifier: verifier,
  });
  if (!token.refreshToken) throw new Error('Too Lost token response did not contain a refresh token.');

  const tokenPath = resolve(process.cwd(), '.env.toolost.local');
  const expiry = typeof token.expiresIn === 'number'
    ? new Date(Date.now() + token.expiresIn * 1000).toISOString()
    : 'not supplied';

  await writeFile(
    tokenPath,
    `# generated by npm run authorize-toolost; expires: ${expiry}\nTOOLOST_ACCESS_TOKEN=${token.accessToken}\nTOOLOST_REFRESH_TOKEN=${token.refreshToken}\n`,
    { encoding: 'utf8', mode: 0o600 },
  );

  console.log(`\naccess token saved to ignored file ${tokenPath}`);
  console.log('copy TOOLOST_CLIENT_ID and TOOLOST_REFRESH_TOKEN into matching GitHub Actions secrets.');
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : 'Too Lost authorization failed.');
  process.exitCode = 1;
});
