#!/usr/bin/env tsx
import { appendFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { config } from 'dotenv';
import { refreshTooLostAccessToken } from '../src/lib/tooLostOAuth';

config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env.toolost.local') });

function requireEnvironment(name: 'TOOLOST_CLIENT_ID' | 'TOOLOST_REFRESH_TOKEN'): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not configured.`);
  return value;
}

function safeEnvironmentValue(value: string): string {
  if (/[\r\n]/.test(value)) throw new Error('Too Lost returned an invalid token value.');
  return value;
}

async function main() {
  const token = await refreshTooLostAccessToken({
    clientId: requireEnvironment('TOOLOST_CLIENT_ID'),
    clientSecret: process.env.TOOLOST_CLIENT_SECRET || undefined,
    refreshToken: requireEnvironment('TOOLOST_REFRESH_TOKEN'),
  });
  if (!token.refreshToken) throw new Error('Too Lost did not rotate the refresh token.');

  const accessToken = safeEnvironmentValue(token.accessToken);
  const refreshToken = safeEnvironmentValue(token.refreshToken);
  const expiry = token.expiresIn
    ? new Date(Date.now() + token.expiresIn * 1000).toISOString()
    : 'not supplied';

  if (process.env.GITHUB_ACTIONS === 'true') {
    console.log(`::add-mask::${accessToken}`);
    console.log(`::add-mask::${refreshToken}`);
  }

  await writeFile(
    resolve(process.cwd(), '.env.toolost.local'),
    `# generated by Too Lost OAuth; expires: ${expiry}\nTOOLOST_ACCESS_TOKEN=${accessToken}\nTOOLOST_REFRESH_TOKEN=${refreshToken}\n`,
    { encoding: 'utf8', mode: 0o600 },
  );

  if (process.env.GITHUB_ENV) {
    await appendFile(process.env.GITHUB_ENV, `TOOLOST_ACCESS_TOKEN=${accessToken}\n`, 'utf8');
  }
  if (process.env.TOOLOST_REFRESH_TOKEN_FILE) {
    await writeFile(process.env.TOOLOST_REFRESH_TOKEN_FILE, refreshToken, { encoding: 'utf8', mode: 0o600 });
  }

  console.log(`Too Lost access token refreshed; expires ${expiry}.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : 'Too Lost token refresh failed.');
  process.exitCode = 1;
});
