// This file is auto-generated by the Spotify API update process
// Last updated: 2025-09-08T19:53:45.675Z

export interface Release {
  id?: string;
  title: string;
  year: string;
  img: string;
  link: string; // Spotify or external link
  releaseDate: string;
  albumType: string;
  slug?: string; // URL-friendly slug for per-release pages
  description?: string; // short description used for metadata
  tracks?: Array<{
    id?: string;
    title: string;
    durationMs?: number;
    duration?: string;
    trackNumber?: number;
    link?: string;
  }>;
  popularity?: number;
  totalTracks?: number;
  genres?: string[];
}

export const staticReleases: Release[] = [
  {
    "id": "5D08C1AIw6zPjPKISbsxJ1",
    "title": "where are you now?",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b27377f49089476a05aba9f11c8f",
    "link": "https://open.spotify.com/album/5D08C1AIw6zPjPKISbsxJ1",
    "releaseDate": "2025-09-05",
    "albumType": "single",
    "slug": "where-are-you-now-5D08C1",
    "description": "where are you now? — single by OKISO.",
    "tracks": [
      {
        "id": "3eCy6HPR031XDxDr910lrp",
        "title": "where are you now?",
        "durationMs": 236571,
        "duration": "PT3M57S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/3eCy6HPR031XDxDr910lrp"
      }
    ],
    "popularity": 0,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "4eMPWLlqqcaJR0HjMZygLK",
    "title": "LOVE LOOP + HEDORO",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273b7e914b7ad13f073e52ac24b",
    "link": "https://open.spotify.com/album/4eMPWLlqqcaJR0HjMZygLK",
    "releaseDate": "2025-08-15",
    "albumType": "single",
    "slug": "love-loop-hedoro-4eMPWL",
    "description": "LOVE LOOP + HEDORO — single by OKISO.",
    "tracks": [
      {
        "id": "0o0QzChjzNroryMSSM2dVU",
        "title": "LOVE LOOP",
        "durationMs": 168022,
        "duration": "PT2M48S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/0o0QzChjzNroryMSSM2dVU"
      },
      {
        "id": "1wxeKuO7kLDt69fHx0Gu1x",
        "title": "HEDORO",
        "durationMs": 201160,
        "duration": "PT3M21S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/1wxeKuO7kLDt69fHx0Gu1x"
      }
    ],
    "popularity": 14,
    "totalTracks": 2,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "1iQHinMs6TsTGr0QYq2TGD",
    "title": "Ochame Kinou (GUMI COVER)",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273335a9f91d4294cb9a3de7af6",
    "link": "https://open.spotify.com/album/1iQHinMs6TsTGr0QYq2TGD",
    "releaseDate": "2025-07-18",
    "albumType": "single",
    "slug": "ochame-kinou-gumi-cover-1iQHin",
    "description": "Ochame Kinou (GUMI COVER) — single by OKISO.",
    "tracks": [
      {
        "id": "0uf4JYCQ0moMPSHAbSRune",
        "title": "Ochame Kinou - GUMI COVER",
        "durationMs": 90075,
        "duration": "PT1M30S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/0uf4JYCQ0moMPSHAbSRune"
      }
    ],
    "popularity": 11,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "5g9YnaSj8JgyxgnfgG3Yz5",
    "title": "MIKU MIKU HATSUNE",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2735aebb8c70854419cedef0ed7",
    "link": "https://open.spotify.com/album/5g9YnaSj8JgyxgnfgG3Yz5",
    "releaseDate": "2025-06-01",
    "albumType": "single",
    "slug": "miku-miku-hatsune-5g9Yna",
    "description": "MIKU MIKU HATSUNE — single by OKISO.",
    "tracks": [
      {
        "id": "3Kglx4iKBUAP0Maqa6vgas",
        "title": "MIKU MIKU HATSUNE",
        "durationMs": 143227,
        "duration": "PT2M23S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/3Kglx4iKBUAP0Maqa6vgas"
      }
    ],
    "popularity": 5,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "15AGWT0YohTDzF5gPCzgw3",
    "title": "RESURRECTION",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273778a4f44c3e5b63f663f87da",
    "link": "https://open.spotify.com/album/15AGWT0YohTDzF5gPCzgw3",
    "releaseDate": "2025-05-25",
    "albumType": "album",
    "slug": "resurrection-15AGWT",
    "description": "RESURRECTION — album by OKISO.",
    "tracks": [
      {
        "id": "7p2nMFW2cIPRSEhYv9hyOR",
        "title": "RESURRECTION",
        "durationMs": 145254,
        "duration": "PT2M25S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/7p2nMFW2cIPRSEhYv9hyOR"
      },
      {
        "id": "4e7QdYyAfZO8nyVGAV5dA4",
        "title": "MIKU MIKU HATSUNE",
        "durationMs": 143227,
        "duration": "PT2M23S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/4e7QdYyAfZO8nyVGAV5dA4"
      },
      {
        "id": "4B7tAixbz8HzoR31bvdxn8",
        "title": "Conquering The World",
        "durationMs": 152437,
        "duration": "PT2M32S",
        "trackNumber": 3,
        "link": "https://open.spotify.com/track/4B7tAixbz8HzoR31bvdxn8"
      },
      {
        "id": "6si0KhQSMHWVpMfE5khwWA",
        "title": "DELICIOUS",
        "durationMs": 111191,
        "duration": "PT1M51S",
        "trackNumber": 4,
        "link": "https://open.spotify.com/track/6si0KhQSMHWVpMfE5khwWA"
      },
      {
        "id": "5dUmzpBAtF5PuQEqu45cOy",
        "title": "ARENA",
        "durationMs": 128593,
        "duration": "PT2M9S",
        "trackNumber": 5,
        "link": "https://open.spotify.com/track/5dUmzpBAtF5PuQEqu45cOy"
      },
      {
        "id": "3KuVsOahgSDlmPPJ221SdM",
        "title": "OUTBURST",
        "durationMs": 126479,
        "duration": "PT2M6S",
        "trackNumber": 6,
        "link": "https://open.spotify.com/track/3KuVsOahgSDlmPPJ221SdM"
      },
      {
        "id": "5oPYtvYePIE0h0L6aYJDHr",
        "title": "NEVER NEEDED HELP",
        "durationMs": 131874,
        "duration": "PT2M12S",
        "trackNumber": 7,
        "link": "https://open.spotify.com/track/5oPYtvYePIE0h0L6aYJDHr"
      },
      {
        "id": "5WYeA5zKH3Y28esmtxaKkr",
        "title": "THE PAIN IS TOO MUCH",
        "durationMs": 159535,
        "duration": "PT2M40S",
        "trackNumber": 8,
        "link": "https://open.spotify.com/track/5WYeA5zKH3Y28esmtxaKkr"
      },
      {
        "id": "0aWT2JpjFVQ8e1VpEoKMJp",
        "title": "I Was Happy Once Again",
        "durationMs": 190959,
        "duration": "PT3M11S",
        "trackNumber": 9,
        "link": "https://open.spotify.com/track/0aWT2JpjFVQ8e1VpEoKMJp"
      },
      {
        "id": "47qBRzhGo8o6zEHHvvC3G9",
        "title": "BORN AGAIN",
        "durationMs": 137660,
        "duration": "PT2M18S",
        "trackNumber": 10,
        "link": "https://open.spotify.com/track/47qBRzhGo8o6zEHHvvC3G9"
      },
      {
        "id": "6wlPJu8bGIvn1rRaH34zNp",
        "title": "Sayonara Wave",
        "durationMs": 146138,
        "duration": "PT2M26S",
        "trackNumber": 11,
        "link": "https://open.spotify.com/track/6wlPJu8bGIvn1rRaH34zNp"
      },
      {
        "id": "6gTLeP0TpS4yC9NzOdnrFr",
        "title": "LEAVE ME ALONE",
        "durationMs": 77156,
        "duration": "PT1M17S",
        "trackNumber": 12,
        "link": "https://open.spotify.com/track/6gTLeP0TpS4yC9NzOdnrFr"
      },
      {
        "id": "530kFQ7ym78SnGNM7oNdcv",
        "title": "I Finally Get To Rest",
        "durationMs": 165982,
        "duration": "PT2M46S",
        "trackNumber": 13,
        "link": "https://open.spotify.com/track/530kFQ7ym78SnGNM7oNdcv"
      },
      {
        "id": "5cRGufjPrJpOt68hUlCVxz",
        "title": "Muimi",
        "durationMs": 177302,
        "duration": "PT2M57S",
        "trackNumber": 14,
        "link": "https://open.spotify.com/track/5cRGufjPrJpOt68hUlCVxz"
      },
      {
        "id": "2bvwLO5EIqgD716FVRvmjD",
        "title": "I Don't Wanna See You Anymore",
        "durationMs": 132339,
        "duration": "PT2M12S",
        "trackNumber": 15,
        "link": "https://open.spotify.com/track/2bvwLO5EIqgD716FVRvmjD"
      },
      {
        "id": "48uiZOcQIPSxv44NBImvXN",
        "title": "ForeverGiga",
        "durationMs": 205825,
        "duration": "PT3M26S",
        "trackNumber": 16,
        "link": "https://open.spotify.com/track/48uiZOcQIPSxv44NBImvXN"
      },
      {
        "id": "5t2Bn0VYlYP5IVhm2xvzvW",
        "title": "ByeBye",
        "durationMs": 126711,
        "duration": "PT2M7S",
        "trackNumber": 17,
        "link": "https://open.spotify.com/track/5t2Bn0VYlYP5IVhm2xvzvW"
      },
      {
        "id": "7AVkYlbSWyTBZsQayWwxHk",
        "title": "Don't Need You",
        "durationMs": 197004,
        "duration": "PT3M17S",
        "trackNumber": 18,
        "link": "https://open.spotify.com/track/7AVkYlbSWyTBZsQayWwxHk"
      },
      {
        "id": "4WdGUk0Rz1PwS1X6T4X930",
        "title": "EDELWEISS",
        "durationMs": 191428,
        "duration": "PT3M11S",
        "trackNumber": 19,
        "link": "https://open.spotify.com/track/4WdGUk0Rz1PwS1X6T4X930"
      },
      {
        "id": "2zKNUuPA8wOu2lYcehzQZ7",
        "title": "And Still We Go On",
        "durationMs": 132839,
        "duration": "PT2M13S",
        "trackNumber": 20,
        "link": "https://open.spotify.com/track/2zKNUuPA8wOu2lYcehzQZ7"
      },
      {
        "id": "62vpxTrO4WfGSkCyTKtlwm",
        "title": "My Dearest",
        "durationMs": 145250,
        "duration": "PT2M25S",
        "trackNumber": 21,
        "link": "https://open.spotify.com/track/62vpxTrO4WfGSkCyTKtlwm"
      },
      {
        "id": "67v2OWm6VnFrVhij0nVl4k",
        "title": "PRIDE DESTRUCTION MACHINE",
        "durationMs": 176678,
        "duration": "PT2M57S",
        "trackNumber": 22,
        "link": "https://open.spotify.com/track/67v2OWm6VnFrVhij0nVl4k"
      },
      {
        "id": "7AJ2PXUsrnq3kZPEzcNCfe",
        "title": "HER",
        "durationMs": 174053,
        "duration": "PT2M54S",
        "trackNumber": 23,
        "link": "https://open.spotify.com/track/7AJ2PXUsrnq3kZPEzcNCfe"
      },
      {
        "id": "141OJztgu0xVizYac0AmuK",
        "title": "ONE MORE TIME",
        "durationMs": 204866,
        "duration": "PT3M25S",
        "trackNumber": 24,
        "link": "https://open.spotify.com/track/141OJztgu0xVizYac0AmuK"
      },
      {
        "id": "6s6X3JLfh3Ri9dQzHoe9cq",
        "title": "The Things That Make This World So Sweet",
        "durationMs": 122942,
        "duration": "PT2M3S",
        "trackNumber": 25,
        "link": "https://open.spotify.com/track/6s6X3JLfh3Ri9dQzHoe9cq"
      }
    ],
    "popularity": 20,
    "totalTracks": 25,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "3gZf6iZobBpU0qk0Ynf9sR",
    "title": "My Dearest",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273478a688a5711326af2e76340",
    "link": "https://open.spotify.com/album/3gZf6iZobBpU0qk0Ynf9sR",
    "releaseDate": "2025-05-01",
    "albumType": "single",
    "slug": "my-dearest-3gZf6i",
    "description": "My Dearest — single by OKISO.",
    "tracks": [
      {
        "id": "1EgZkfaD05SjyeXN16bnnw",
        "title": "My Dearest",
        "durationMs": 142500,
        "duration": "PT2M23S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/1EgZkfaD05SjyeXN16bnnw"
      }
    ],
    "popularity": 1,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "2lmc5y1ZnzgSyKzyZOux6q",
    "title": "FANTASIA & ETUDE",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273f9828b8b052d94e53344ee27",
    "link": "https://open.spotify.com/album/2lmc5y1ZnzgSyKzyZOux6q",
    "releaseDate": "2025-04-25",
    "albumType": "album",
    "slug": "fantasia-etude-2lmc5y",
    "description": "FANTASIA & ETUDE — album by OKISO.",
    "tracks": [
      {
        "id": "2X5r22R4iCnKaAAp16qyQ5",
        "title": "FANTASIA & ETUDE",
        "durationMs": 191799,
        "duration": "PT3M12S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/2X5r22R4iCnKaAAp16qyQ5"
      },
      {
        "id": "5UFN7cqbjxJOwuqSE72YsW",
        "title": "Meet The Princess",
        "durationMs": 146350,
        "duration": "PT2M26S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/5UFN7cqbjxJOwuqSE72YsW"
      },
      {
        "id": "1fVrAMfXz0eCiEuoqtxBNL",
        "title": "Your Every Weird Ways",
        "durationMs": 193201,
        "duration": "PT3M13S",
        "trackNumber": 3,
        "link": "https://open.spotify.com/track/1fVrAMfXz0eCiEuoqtxBNL"
      },
      {
        "id": "6btgJhIsjdS3sRHnUjOJdz",
        "title": "I Want To Be A Villain",
        "durationMs": 114566,
        "duration": "PT1M55S",
        "trackNumber": 4,
        "link": "https://open.spotify.com/track/6btgJhIsjdS3sRHnUjOJdz"
      },
      {
        "id": "2xCrpqRdM03vg017pKasrh",
        "title": "PRECIOUS YOU",
        "durationMs": 141711,
        "duration": "PT2M22S",
        "trackNumber": 5,
        "link": "https://open.spotify.com/track/2xCrpqRdM03vg017pKasrh"
      },
      {
        "id": "1TlDD8VWiHowIjNaPX5qs5",
        "title": "BLOW IT ALL UP",
        "durationMs": 205383,
        "duration": "PT3M25S",
        "trackNumber": 6,
        "link": "https://open.spotify.com/track/1TlDD8VWiHowIjNaPX5qs5"
      },
      {
        "id": "0NqPZZqieNnQWTc1JaZKRx",
        "title": "Betrayal",
        "durationMs": 139235,
        "duration": "PT2M19S",
        "trackNumber": 7,
        "link": "https://open.spotify.com/track/0NqPZZqieNnQWTc1JaZKRx"
      }
    ],
    "popularity": 23,
    "totalTracks": 7,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "4NEgkpLoPck8FGujMpa4na",
    "title": "voidroid",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273236c5e927ae8bac15ed1eaa9",
    "link": "https://open.spotify.com/album/4NEgkpLoPck8FGujMpa4na",
    "releaseDate": "2025-04-15",
    "albumType": "single",
    "slug": "voidroid-4NEgkp",
    "description": "voidroid — single by OKISO.",
    "tracks": [
      {
        "id": "5R5w62sI8UlpbYRSl2Ipnb",
        "title": "voidroid",
        "durationMs": 120000,
        "duration": "PT2M0S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/5R5w62sI8UlpbYRSl2Ipnb"
      }
    ],
    "popularity": 2,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "4raTOoWiHkOwYH7CQFzAcC",
    "title": "ETUDE",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273d801af2d510e722d0444a16f",
    "link": "https://open.spotify.com/album/4raTOoWiHkOwYH7CQFzAcC",
    "releaseDate": "2025-04-07",
    "albumType": "album",
    "slug": "etude-4raTOo",
    "description": "ETUDE — album by OKISO.",
    "tracks": [
      {
        "id": "7HM8bAQBLKsqKZZI9OxWF5",
        "title": "ETUDE",
        "durationMs": 128231,
        "duration": "PT2M8S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/7HM8bAQBLKsqKZZI9OxWF5"
      },
      {
        "id": "0BDA6bKgu30q2ksFuarSSf",
        "title": "DESTINY",
        "durationMs": 150442,
        "duration": "PT2M30S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/0BDA6bKgu30q2ksFuarSSf"
      },
      {
        "id": "2dslSYo74220g8MhU2caxR",
        "title": "DREAMING",
        "durationMs": 103581,
        "duration": "PT1M44S",
        "trackNumber": 3,
        "link": "https://open.spotify.com/track/2dslSYo74220g8MhU2caxR"
      },
      {
        "id": "12mFsBm156dtsft1vOxTO7",
        "title": "Never Mind, We Trippin'",
        "durationMs": 134638,
        "duration": "PT2M15S",
        "trackNumber": 4,
        "link": "https://open.spotify.com/track/12mFsBm156dtsft1vOxTO7"
      },
      {
        "id": "4YWpZOA1QMPkehQ3eoveNh",
        "title": "What's Your Dream?",
        "durationMs": 134799,
        "duration": "PT2M15S",
        "trackNumber": 5,
        "link": "https://open.spotify.com/track/4YWpZOA1QMPkehQ3eoveNh"
      },
      {
        "id": "5rukVcb27kbfdvTuwZBRrw",
        "title": "FEAR",
        "durationMs": 169482,
        "duration": "PT2M49S",
        "trackNumber": 6,
        "link": "https://open.spotify.com/track/5rukVcb27kbfdvTuwZBRrw"
      },
      {
        "id": "3uO5a5Qpt5JeIwC8QCOGCq",
        "title": "Life's a Quest",
        "durationMs": 146250,
        "duration": "PT2M26S",
        "trackNumber": 7,
        "link": "https://open.spotify.com/track/3uO5a5Qpt5JeIwC8QCOGCq"
      },
      {
        "id": "75CcP80AIujRJdJ6kuO2Fq",
        "title": "GOD COMPLEX",
        "durationMs": 92294,
        "duration": "PT1M32S",
        "trackNumber": 8,
        "link": "https://open.spotify.com/track/75CcP80AIujRJdJ6kuO2Fq"
      },
      {
        "id": "09TWC08E06oIE60LN3B7bg",
        "title": "TEARS IN HEAVEN '99",
        "durationMs": 146384,
        "duration": "PT2M26S",
        "trackNumber": 9,
        "link": "https://open.spotify.com/track/09TWC08E06oIE60LN3B7bg"
      },
      {
        "id": "155yiTOZa1UfpDeDgF5Fj4",
        "title": "1 to 10",
        "durationMs": 111870,
        "duration": "PT1M52S",
        "trackNumber": 10,
        "link": "https://open.spotify.com/track/155yiTOZa1UfpDeDgF5Fj4"
      },
      {
        "id": "0C0PPLRRIvNHsFX8DLkTuy",
        "title": "Liveliness Within",
        "durationMs": 176727,
        "duration": "PT2M57S",
        "trackNumber": 11,
        "link": "https://open.spotify.com/track/0C0PPLRRIvNHsFX8DLkTuy"
      }
    ],
    "popularity": 20,
    "totalTracks": 11,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "3WBZF8QXXRebLD0cud4KTQ",
    "title": "HELLO, WORLD.",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273b1a3e2b49011da734655b332",
    "link": "https://open.spotify.com/album/3WBZF8QXXRebLD0cud4KTQ",
    "releaseDate": "2025-03-25",
    "albumType": "single",
    "slug": "hello-world-3WBZF8",
    "description": "HELLO, WORLD. — single by OKISO.",
    "tracks": [
      {
        "id": "1gFggdnwffrhNtmi8A7KdC",
        "title": "HELLO, WORLD.",
        "durationMs": 120485,
        "duration": "PT2M0S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/1gFggdnwffrhNtmi8A7KdC"
      }
    ],
    "popularity": 5,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "3tQfs4MH0zc8bVk9Inv2hT",
    "title": "Meet The Princess",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b27359b538de2a62ef053fa5b1d9",
    "link": "https://open.spotify.com/album/3tQfs4MH0zc8bVk9Inv2hT",
    "releaseDate": "2025-03-18",
    "albumType": "single",
    "slug": "meet-the-princess-3tQfs4",
    "description": "Meet The Princess — single by OKISO.",
    "tracks": [
      {
        "id": "08lgR4gIVOuWZDUGUcFnvW",
        "title": "Meet The Princess",
        "durationMs": 146350,
        "duration": "PT2M26S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/08lgR4gIVOuWZDUGUcFnvW"
      }
    ],
    "popularity": 2,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "6JZQro8zNEHUfEFZuVFMrC",
    "title": "SHUT OFF",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273b05416788a9b6001b4424116",
    "link": "https://open.spotify.com/album/6JZQro8zNEHUfEFZuVFMrC",
    "releaseDate": "2025-03-15",
    "albumType": "single",
    "slug": "shut-off-6JZQro",
    "description": "SHUT OFF — single by OKISO.",
    "tracks": [
      {
        "id": "7I92OUNaj0Alp58oKpcAHR",
        "title": "SHUT OFF",
        "durationMs": 81754,
        "duration": "PT1M22S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/7I92OUNaj0Alp58oKpcAHR"
      }
    ],
    "popularity": 3,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "0t28Vt3fN6awEEFcTR3AlN",
    "title": "FANTASIA",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2734bcdda5555ac77a5b56c91b2",
    "link": "https://open.spotify.com/album/0t28Vt3fN6awEEFcTR3AlN",
    "releaseDate": "2025-03-10",
    "albumType": "album",
    "slug": "fantasia-0t28Vt",
    "description": "FANTASIA — album by OKISO.",
    "tracks": [
      {
        "id": "7DhmlwtRmIKWfK2nBMs825",
        "title": "FANTASIA",
        "durationMs": 195062,
        "duration": "PT3M15S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/7DhmlwtRmIKWfK2nBMs825"
      },
      {
        "id": "0YSik8n8DrFno0xhR5kpg1",
        "title": "Keep On",
        "durationMs": 162683,
        "duration": "PT2M43S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/0YSik8n8DrFno0xhR5kpg1"
      },
      {
        "id": "7opxxI38lLHhbVkgyxQo93",
        "title": "MANGO BOBA",
        "durationMs": 176283,
        "duration": "PT2M56S",
        "trackNumber": 3,
        "link": "https://open.spotify.com/track/7opxxI38lLHhbVkgyxQo93"
      },
      {
        "id": "2xyiojd85EdFhAE8e9zO5W",
        "title": "ONLINE",
        "durationMs": 168312,
        "duration": "PT2M48S",
        "trackNumber": 4,
        "link": "https://open.spotify.com/track/2xyiojd85EdFhAE8e9zO5W"
      },
      {
        "id": "4Af9nxq0lss6t2apwOX9E0",
        "title": "LIGHT AND DARK",
        "durationMs": 146437,
        "duration": "PT2M26S",
        "trackNumber": 5,
        "link": "https://open.spotify.com/track/4Af9nxq0lss6t2apwOX9E0"
      },
      {
        "id": "2Wn1AVUhUGfJTkZZqQTQE9",
        "title": "Pretty Blue-Eyed Blonde",
        "durationMs": 141776,
        "duration": "PT2M22S",
        "trackNumber": 6,
        "link": "https://open.spotify.com/track/2Wn1AVUhUGfJTkZZqQTQE9"
      },
      {
        "id": "1GrbgBhkF4Gi5LFoegg1JF",
        "title": "Meaningless World",
        "durationMs": 138889,
        "duration": "PT2M19S",
        "trackNumber": 7,
        "link": "https://open.spotify.com/track/1GrbgBhkF4Gi5LFoegg1JF"
      },
      {
        "id": "40rqPOOU8GWqV6XiZWgxFa",
        "title": "I Want To Live",
        "durationMs": 227799,
        "duration": "PT3M48S",
        "trackNumber": 8,
        "link": "https://open.spotify.com/track/40rqPOOU8GWqV6XiZWgxFa"
      }
    ],
    "popularity": 15,
    "totalTracks": 8,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "7uIGVdqJrhTWRyVJfB8bo6",
    "title": "ANOTHER LIFE (Remix)",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273a2658b2a9a9c1d2255482304",
    "link": "https://open.spotify.com/album/7uIGVdqJrhTWRyVJfB8bo6",
    "releaseDate": "2025-03-03",
    "albumType": "single",
    "slug": "another-life-remix-7uIGVd",
    "description": "ANOTHER LIFE (Remix) — single by OKISO.",
    "tracks": [
      {
        "id": "6f4eNccxDULuNatvBUSDyF",
        "title": "ANOTHER LIFE - Remix",
        "durationMs": 152990,
        "duration": "PT2M33S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/6f4eNccxDULuNatvBUSDyF"
      }
    ],
    "popularity": 3,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "74Gn18pzYvHn1ZWIjEs1mI",
    "title": "PRECIOUS YOU",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2737cf45af28a4e3f4698b05723",
    "link": "https://open.spotify.com/album/74Gn18pzYvHn1ZWIjEs1mI",
    "releaseDate": "2025-02-25",
    "albumType": "single",
    "slug": "precious-you-74Gn18",
    "description": "PRECIOUS YOU — single by OKISO.",
    "tracks": [
      {
        "id": "0AfViJ0ogCGfWkukMop215",
        "title": "PRECIOUS YOU",
        "durationMs": 141711,
        "duration": "PT2M22S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/0AfViJ0ogCGfWkukMop215"
      }
    ],
    "popularity": 3,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "0jLZeVoHNqheN7rYfCIO9A",
    "title": "TEARS IN HEAVEN '99",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2732ba246a8437bdd963b6ceca3",
    "link": "https://open.spotify.com/album/0jLZeVoHNqheN7rYfCIO9A",
    "releaseDate": "2025-02-17",
    "albumType": "single",
    "slug": "tears-in-heaven-99-0jLZeV",
    "description": "TEARS IN HEAVEN '99 — single by OKISO.",
    "tracks": [
      {
        "id": "7MSF2M74ytHesGgWHl52fJ",
        "title": "TEARS IN HEAVEN '99",
        "durationMs": 146384,
        "duration": "PT2M26S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/7MSF2M74ytHesGgWHl52fJ"
      }
    ],
    "popularity": 2,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "6vU5gaWqNZKNl3V9pkjsEI",
    "title": "MANGO BOBA",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273e152bb5d2bac32afccf48a15",
    "link": "https://open.spotify.com/album/6vU5gaWqNZKNl3V9pkjsEI",
    "releaseDate": "2025-02-13",
    "albumType": "single",
    "slug": "mango-boba-6vU5ga",
    "description": "MANGO BOBA — single by OKISO.",
    "tracks": [
      {
        "id": "6YY2Iq6gOBI4G3esiKvV5i",
        "title": "MANGO BOBA",
        "durationMs": 176283,
        "duration": "PT2M56S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/6YY2Iq6gOBI4G3esiKvV5i"
      }
    ],
    "popularity": 1,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "20BzwSTaHHb6CDKhGzWHiQ",
    "title": "FEAR",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2739b73074b371f4e08348fbfc6",
    "link": "https://open.spotify.com/album/20BzwSTaHHb6CDKhGzWHiQ",
    "releaseDate": "2025-02-13",
    "albumType": "single",
    "slug": "fear-20BzwS",
    "description": "FEAR — single by OKISO.",
    "tracks": [
      {
        "id": "6LscaIjv0Lckj9itcdOvqg",
        "title": "FEAR",
        "durationMs": 169482,
        "duration": "PT2M49S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/6LscaIjv0Lckj9itcdOvqg"
      }
    ],
    "popularity": 1,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "2pttuX0SUW3BC8JHjVn2S0",
    "title": "DESTINY",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273e7e96cffbcb690cbe3c09c3e",
    "link": "https://open.spotify.com/album/2pttuX0SUW3BC8JHjVn2S0",
    "releaseDate": "2025-02-07",
    "albumType": "single",
    "slug": "destiny-2pttuX",
    "description": "DESTINY — single by OKISO.",
    "tracks": [
      {
        "id": "4VwDOFv0F85dwFnahuNhXI",
        "title": "DESTINY",
        "durationMs": 150442,
        "duration": "PT2M30S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/4VwDOFv0F85dwFnahuNhXI"
      }
    ],
    "popularity": 3,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "1nQYgQ3t6OvbI61a72h9bX",
    "title": "REVOLUTION",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b27311579e9278b6f267402f2fbb",
    "link": "https://open.spotify.com/album/1nQYgQ3t6OvbI61a72h9bX",
    "releaseDate": "2025-01-25",
    "albumType": "album",
    "slug": "revolution-1nQYgQ",
    "description": "REVOLUTION — album by OKISO.",
    "tracks": [
      {
        "id": "716gnBAFIoycoEpPZwCdbl",
        "title": "REVOLUTION",
        "durationMs": 99403,
        "duration": "PT1M39S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/716gnBAFIoycoEpPZwCdbl"
      },
      {
        "id": "3sPoLdzeQGWQZdUb1Y79Bd",
        "title": "TRUST",
        "durationMs": 116774,
        "duration": "PT1M57S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/3sPoLdzeQGWQZdUb1Y79Bd"
      },
      {
        "id": "59E62b4T9uORsjvWZsjn7D",
        "title": "NEVER DIE",
        "durationMs": 183048,
        "duration": "PT3M3S",
        "trackNumber": 3,
        "link": "https://open.spotify.com/track/59E62b4T9uORsjvWZsjn7D"
      },
      {
        "id": "2P02a1o5sPchIj7cpa0Oq7",
        "title": "TIRED",
        "durationMs": 128084,
        "duration": "PT2M8S",
        "trackNumber": 4,
        "link": "https://open.spotify.com/track/2P02a1o5sPchIj7cpa0Oq7"
      },
      {
        "id": "6Rd0BZcKllPZS3X6o4a27M",
        "title": "PARADIGM",
        "durationMs": 107812,
        "duration": "PT1M48S",
        "trackNumber": 5,
        "link": "https://open.spotify.com/track/6Rd0BZcKllPZS3X6o4a27M"
      },
      {
        "id": "1LqqYGhocHWYZnVWltBBWj",
        "title": "YOU FOUND ME",
        "durationMs": 161644,
        "duration": "PT2M42S",
        "trackNumber": 6,
        "link": "https://open.spotify.com/track/1LqqYGhocHWYZnVWltBBWj"
      },
      {
        "id": "6NgBBIEHko3e3zZ6K6h5Bw",
        "title": "I WANNA LOVE YOU",
        "durationMs": 194913,
        "duration": "PT3M15S",
        "trackNumber": 7,
        "link": "https://open.spotify.com/track/6NgBBIEHko3e3zZ6K6h5Bw"
      },
      {
        "id": "1WFCDh4hM7SzD0XJhGdAEW",
        "title": "ONCE AND FOR ALL",
        "durationMs": 93105,
        "duration": "PT1M33S",
        "trackNumber": 8,
        "link": "https://open.spotify.com/track/1WFCDh4hM7SzD0XJhGdAEW"
      }
    ],
    "popularity": 18,
    "totalTracks": 8,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "72PR4fh7pB0VDoUenr26uK",
    "title": "IN YOUR PRESENCE",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2739c3d81399abff94842117ce3",
    "link": "https://open.spotify.com/album/72PR4fh7pB0VDoUenr26uK",
    "releaseDate": "2025-01-24",
    "albumType": "single",
    "slug": "in-your-presence-72PR4f",
    "description": "IN YOUR PRESENCE — single by OKISO.",
    "tracks": [
      {
        "id": "6LLSGGR5lyhyYmZBcUQ9Xx",
        "title": "IN YOUR PRESENCE",
        "durationMs": 137557,
        "duration": "PT2M18S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/6LLSGGR5lyhyYmZBcUQ9Xx"
      },
      {
        "id": "6ug8UvxztvDEKKeV9QjsOJ",
        "title": "I DONT FEEL IT ANYMORE - outro",
        "durationMs": 105235,
        "duration": "PT1M45S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/6ug8UvxztvDEKKeV9QjsOJ"
      }
    ],
    "popularity": 0,
    "totalTracks": 2,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "74fSXSvQZlYItgFeWBOWIE",
    "title": "MACHINE GUN",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273e88f4d805ba5f8d2a302efa1",
    "link": "https://open.spotify.com/album/74fSXSvQZlYItgFeWBOWIE",
    "releaseDate": "2025-01-17",
    "albumType": "single",
    "slug": "machine-gun-74fSXS",
    "description": "MACHINE GUN — single by OKISO.",
    "tracks": [
      {
        "id": "33OCFuEeeKSJGYFydy60aV",
        "title": "MACHINE GUN",
        "durationMs": 140322,
        "duration": "PT2M20S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/33OCFuEeeKSJGYFydy60aV"
      }
    ],
    "popularity": 2,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "3dhdyjSH3EG8YMFaHdmBw0",
    "title": "REVENGE",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b2737b4bb19ded8f9653f7e0e5cc",
    "link": "https://open.spotify.com/album/3dhdyjSH3EG8YMFaHdmBw0",
    "releaseDate": "2025-01-07",
    "albumType": "single",
    "slug": "revenge-3dhdyj",
    "description": "REVENGE — single by OKISO.",
    "tracks": [
      {
        "id": "3DVTLR9ZeTGtNh76MBaoGw",
        "title": "REVENGE",
        "durationMs": 116509,
        "duration": "PT1M57S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/3DVTLR9ZeTGtNh76MBaoGw"
      }
    ],
    "popularity": 5,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "3sMC9TVo5SHEpGV0WuyYJm",
    "title": "FLY",
    "year": "2025",
    "img": "https://i.scdn.co/image/ab67616d0000b273c19b0fa854ea3cc6e899846a",
    "link": "https://open.spotify.com/album/3sMC9TVo5SHEpGV0WuyYJm",
    "releaseDate": "2025-01-03",
    "albumType": "single",
    "slug": "fly-3sMC9T",
    "description": "FLY — single by OKISO.",
    "tracks": [
      {
        "id": "6FkUk5eljfLWwPyVaSkNN8",
        "title": "FLY",
        "durationMs": 123857,
        "duration": "PT2M4S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/6FkUk5eljfLWwPyVaSkNN8"
      }
    ],
    "popularity": 0,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "5Debz7V0TMizIqlRCnQtad",
    "title": "THUNDER",
    "year": "2024",
    "img": "https://i.scdn.co/image/ab67616d0000b27332c94f834b9b57fb20f4bcc2",
    "link": "https://open.spotify.com/album/5Debz7V0TMizIqlRCnQtad",
    "releaseDate": "2024-12-26",
    "albumType": "single",
    "slug": "thunder-5Debz7",
    "description": "THUNDER — single by OKISO.",
    "tracks": [
      {
        "id": "00EsrgNiZTIOqfR7xx3aUI",
        "title": "THUNDER",
        "durationMs": 149860,
        "duration": "PT2M30S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/00EsrgNiZTIOqfR7xx3aUI"
      }
    ],
    "popularity": 0,
    "totalTracks": 1,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "1K4cNRy6VPwaVV6VgE6Cbx",
    "title": "PRIDE",
    "year": "2024",
    "img": "https://i.scdn.co/image/ab67616d0000b273da882f8839ef2515bb754da7",
    "link": "https://open.spotify.com/album/1K4cNRy6VPwaVV6VgE6Cbx",
    "releaseDate": "2024-12-15",
    "albumType": "single",
    "slug": "pride-1K4cNR",
    "description": "PRIDE — single by OKISO.",
    "tracks": [
      {
        "id": "00OQxyZrsM3Cni1Ku34NIp",
        "title": "PRIDE",
        "durationMs": 147697,
        "duration": "PT2M28S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/00OQxyZrsM3Cni1Ku34NIp"
      },
      {
        "id": "2EkxgKMjU0IiOy3nfhQn5t",
        "title": "what's your \"why\"? - outro",
        "durationMs": 96927,
        "duration": "PT1M37S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/2EkxgKMjU0IiOy3nfhQn5t"
      }
    ],
    "popularity": 0,
    "totalTracks": 2,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "4ZnFA6BezUO6Sd3EBRrten",
    "title": "Watashi Wa Dare",
    "year": "2024",
    "img": "https://i.scdn.co/image/ab67616d0000b2736cb81ad6535ef78c99da900d",
    "link": "https://open.spotify.com/album/4ZnFA6BezUO6Sd3EBRrten",
    "releaseDate": "2024-03-26",
    "albumType": "single",
    "slug": "watashi-wa-dare-4ZnFA6",
    "description": "Watashi Wa Dare — single by OKISO.",
    "tracks": [
      {
        "id": "0FZmSZLGhF3qBSDBqECzM1",
        "title": "Watashi Wa Dare",
        "durationMs": 94249,
        "duration": "PT1M34S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/0FZmSZLGhF3qBSDBqECzM1"
      },
      {
        "id": "0GoZFJDFro5gkNJacbd0ce",
        "title": "Watashi Wa Dare - Instrumental",
        "durationMs": 130783,
        "duration": "PT2M11S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/0GoZFJDFro5gkNJacbd0ce"
      }
    ],
    "popularity": 0,
    "totalTracks": 2,
    "genres": [
      "vocaloid"
    ]
  },
  {
    "id": "13zLY9ytK7dqXJTPH3bvSv",
    "title": "Star Trail",
    "year": "2024",
    "img": "https://i.scdn.co/image/ab67616d0000b273322cbf0dd700345ea3aca5b2",
    "link": "https://open.spotify.com/album/13zLY9ytK7dqXJTPH3bvSv",
    "releaseDate": "2024-03-18",
    "albumType": "single",
    "slug": "star-trail-13zLY9",
    "description": "Star Trail — single by OKISO.",
    "tracks": [
      {
        "id": "4FGeNBsxUWWb9S2r3JmAuK",
        "title": "Star Trail",
        "durationMs": 145901,
        "duration": "PT2M26S",
        "trackNumber": 1,
        "link": "https://open.spotify.com/track/4FGeNBsxUWWb9S2r3JmAuK"
      },
      {
        "id": "6Sn5PxRLSrtH6LJKjfFTjf",
        "title": "Star Trail - Instrumental",
        "durationMs": 147406,
        "duration": "PT2M27S",
        "trackNumber": 2,
        "link": "https://open.spotify.com/track/6Sn5PxRLSrtH6LJKjfFTjf"
      }
    ],
    "popularity": 0,
    "totalTracks": 2,
    "genres": [
      "vocaloid"
    ]
  }
];
