name: Update Spotify Releases

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if no changes detected'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-releases:
    runs-on: ubuntu-latest
    name: Update Spotify Releases Data
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update releases data
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: npm run update-releases
          
      - name: Check for changes
        id: git-check
        run: |
          git add src/data/releases.ts
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in releases data"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in releases data"
          fi
          
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/releases.ts
          git commit -m "🎵 Auto-update Spotify releases data"
          git push
